#Questions are based off of the ASI as best as I could do with keeping the questions in a logical flow. There are 81 questions total, which I feel like may need to be scaled down or separate them into different categories.


import time
print("Addiction Severity Index, based on 5th Addition")
total = []


#UPDATE: I've gone ahead and just did all questions that had 5 answer choices for now that made sense in order
questions = ['1. How many times in your life have you been hospitalized for medical problems? Include ODs and DTs. Exclude detox, alcohol/drug, psychiatric treatment, and childbirth (if no complications). Enter the number of overnight hospitalizations for medical problems.',         
            '2. How long ago was your last hospitalization for physical problem?',
            '3. How many days have you experienced medical problems in the past 30 days? Include flue, colds, etc. Include serious ailments related to drugs/alcohol, which would continue even if the patient were abstinent (e.g., cirrhosis of liver, abscesses for needles).',
            '4. How troubled or bothered have you been by these medical problems in the past 30 days?',
            '5. How important to you is treatment for these medical problems?',
            '6. How many days in the past 30 days have you used alcohol?',
            '7. How many years in your life have you regularly used alcohol?',
            '8. How many days in the past 30 days have you used alcohol to intoxication?',
            '9. How many years in your life have you regularly used alcohol to intoxication?',
            '10. How many days in the past 30 days have you used heroin?',
            '11. How many years in your life have you regularly used heroin?',
            '12. How many days in the past 30 days have you used methadone?',
            '13. How many years in your life have you regularly used methadone?',
            '14. How many days in the past 30 days have you used other opiates/analgesics?',
            '15. How many years in your life have you regularly used other opiates/analgesics?',
            '16. How many days in the past 30 days have you used barbiturates?',
            '17. How many years in your life have you regularly used barbiturates?',
            '18. How many days in the past 30 days have you used sedatives/hypnotics/tranquilizers?',
            '19. How many years in your life have you regularly used sedatives/hypnotics/tranquilizers?',
            '20. How many days in the past 30 days have you used cocaine?',
            '21. How many years in your life have you regularly used cocaine?',
            '22. How many days in the past 30 days have you used amphetamines?',
            '23. How many years in your life have you regularly used amphetamines?',
            '24. How many days in the past 30 days have you used cannabis?',
            '25. How many years in your life have you regularly used cannabis?',
            '26. How many days in the past 30 days have you used hallucinogens?',
            '27. How many years in your life have you regularly used hallucinogens?',
            '28. How many days in the past 30 days have you used inhalants?',
            '29. How many years in your life have you regularly used inhalants?',
            '30. How many days in the past 30 days have you used more than one substance per day (including alcohol)?',
            '31. How many years in your life have you regularly used more than one substance per day (including alcohol)?',
            '32. How many times have you had alcohol DTs? (Delirium Tremens occur 24-48 hours after last drink or significant decrease in alcohol intake; includes shaking, severe disorientation, fever, hallucinations. DTs usually require medical attention.)',
            '33. How many times have you overdosed on drugs? Overdoses requires intervention by someone to recover, not simply sleeping it off; include suicide attempts by OD.',
            '34. How many times in your life have you been treated for alcohol abuse?',
            '35. How many times in your life have you been treated for drug abuse? Include detoxification, halfway houses, in/outpatient counseling, and AA or NA (if 3+ meetings within 1-month period).',
            '36. How much money would you say you spent during the past 30 days on alcohol?',
            '37. How much money would you say you spent during the past 30 on drugs? (Count only actual money spent)',
            '38. How many days have you been treated in an outpaient setting for alcohol or drugs in the past 30 days? (Include AA/NA)',
            '39. How many days in the past 30 days have you experienced alcohol problems?',
            '40. How many days in the past 30 days have you experienced drug problems? (Include: Craving, withdrawl symptoms, disturbing effects of use, or wanting to stop and being unable to.)',
            '41. How troubled or bothered have you been in the past 30 days by alcohol problems?',
            '42. How troubled or bothered have you been in the past 30 days by drug problems?',
            '43. How important to you now is treatment for alcohol problems?',
            '44. How important to you now is treatment for drug problems?',
            '45. How many times in your life have you been arrested and charged with shoplifting/vandalism?',
            '46. How many times in your life have you been arrested and charged with parole/probation violations?',
            '47. How many times in your life have you been arrested and charged with drug charges?',
            '48. How many times in your life have you been arrested and charged with forgery?',
            '49. How many times in your life have you been arrested and charged with weapons offense?',
            '50. How many times in your life have you been arrested and charged with burglary/larceny/breaking and entering?',
            '51. How many times in your life have you been arrested and charged with robbery? (Include total number of counts, not just convictions. Do not include juvenile (pre age 18) crimes, unless client was charged as an adult. Include formal charges only.)',
            '52. How many times in your life have you been arrested and charged with assult?',
            '53. How many times in your life have you been arrested and charged with arson?',
            '54. How many times in your life have you been arrested and charged with rape?',
            '55. How many times in your life have you been arrested and charged with homicide/manslaughter?',
            '56. How many times in your life have you been arrested and charged with prostitution?',
            '57. How many times in your life have you been arrested and charged with contempt of court?',
            '58. How many days in the past 30 days have you engaged in illegal activites for profit? (Exclude simple drug possession. Include drug dealing, prostitution, selling stolen good, etc.)',
            '59. How serious do you feel your present legal problems are? (Exclude civil problems)',
            '60. How important to you now is counseling or referral for these legal problems? (Paitent is rating a need for additional referral to legal counsel for dense against criminal charges)',
            '61. How many days in the past 30 days have you had serious conflicts with your family?',
            '62. How many daysin the past 30 days have you had serious conflicts with other people (excluding family)?',
            '63. How troubled or bothered have you been in the past 30 days by family problems?',
            '64. How troubled or bothered have you been in the past 30 days by social problems?',
            '65. How important to you now is treatment or counceling for family problems? (You are rating your need for counseling for family problems, not whether the patient would be willing to attend.)',
            '66. How important to you now is treatment or counseling for social problems? (Include your need to seek treatment for such social problems as loneliness, inability to socialize, and dissatisfaction with friends. Your rating should refer to dissatisfaction, conflicts, or other serious problems.)',
            '67. How many times have you been treated for any psychological or emotional problems in a hospital or impatient setting?',
            '68. How many times have you been treated for any phychological or emotional problems as an outpatient/private patient? (Do not include substance abuse, employment, or family counseling. Treatment episode = a series of more or less continuous visits or treatment days, not hte number of visits or treatment days.)',
            '69. How many days in the past 30 days have you experienced these psychologival or emotional problems?',
            '70. How much have your been troubled or bothered by these psychological or emotional problems in the past 30 days?',
            '71. How important to you now is treatment for these psychological or emotional problems?']

#once I figure out the number of answers for each question, this will be the first answer for each question or "a"
ans0 = ['0-1',
        'Never',
        '0 – 6 days',
        'Not at all',
        'Not at all',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0 – 6 days',
        '0 – 6 years',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        'None',
        'None',
        '0 – 6 days',
        '0 – 6 days',
        '0 – 6 days',
        'Not at all',
        'Not at all',
        'Not at all',
        'Not at all',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0-1',
        '0 – 6 days',
        'Not at all',
        'Not at all',
        '0 – 6 days',
        '0 – 6 days',
        'Not at all',
        'Not at all',
        'Not at all',
        'Not at all',
        '0-1',
        '0-1',
        '0 – 6 days',
        'Not at all',
        'Not at all']
#this will be the second answer for each question or "b"
ans1 = ['2-3',
        '1 – 3 months',
        '7 – 12 days',
        'Slightly',
        'Slightly',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '7 – 12 days',
        '7 – 12 years',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '$1-$50',
        '$1-$50',
        '7 – 12 days',
        '7 – 12 days',
        '7 – 12 days',
        'Slightly',
        'Slightly',
        'Slightly',
        'Slightly',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '2-3',
        '7 – 12 days',
        'Slightly',
        'Slightly',
        '7 – 12 days',
        '7 – 12 days',
        'Slightly',
        'Slightly',
        'Slightly',
        'Slightly',
        '2-3',
        '2-3',
        '7 – 12 days',
        'Slightly',
        'Slightly']
#this will be the third answer for each question or "c"
ans2 = ['4-5',
        '4 – 6 months',
        '13 – 18 days',
        'Moderately',
        'Moderately',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '13 – 18 days',
        '13 – 18 years',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '$51-$100',
        '$51-$100',
        '13 – 18 days',
        '13 – 18 days',
        '13 – 18 days',
        'Moderately',
        'Moderately',
        'Moderately',
        'Moderately',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '4-5',
        '13 – 18 days',
        'Moderately',
        'Moderately',
        '13 – 18 days',
        '13 – 18 days',
        'Moderately',
        'Moderately',
        'Moderately',
        'Moderately',
        '4-5',
        '4-5',
        '13 – 18 days',
        'Moderately',
        'Moderately']
ans3 = ['6-7',
        '7 – 9 months',
        '19 – 24 days',
        'Considerably',
        'Considerably',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '19 – 24 days',
        '19 – 24 years',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '$101-$150',
        '$101-$150',
        '19 – 24 days',
        '19 – 24 days',
        '19 – 24 days',
        'Considerably',
        'Considerably',
        'Considerably',
        'Considerably',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '6-7',
        '19 – 24 days',
        'Considerably',
        'Considerably',
        '19 – 24 days',
        '19 – 24 days',
        'Considerable',
        'Considerable',
        'Considerable',
        'Considerable',
        '6-7',
        '6-7',
        '19 – 24 days',
        'Considerable',
        'Considerable']
ans4 = ['8+',
        '10+ months',
        '25+ days',
        'Extremely',
        'Extremely',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
       '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '25+ days',
        '25+ years',
        '8+',
        '8+',
        '8+',
        '8+',
        '$151+',
        '$151+',
        '25+ days',
        '25+ days',
        '25+ days',
        'Extremely',
        'Extremely',
        'Extremely',
        'Extremely',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '8+',
        '25+ days',
        'Extremely',
        'Extremely',
        '25+ days',
        '25+ days',
        'Extremely',
        'Extremely',
        'Extremely',
        'Extremely',
        '8+',
        '8+',
        '25+ days',
        'Extremely',
        'Extremely']

def questionaire():
    rounds = 0
    while rounds < 71: #this is the number of questions I have
        print('Question ')
        print(rounds + 1)
        print(questions[rounds] + ':')
        print('1 :' + ans0[rounds])
        print('2 :' + ans1[rounds])
        print('3 :' + ans2[rounds])
        print('4 :' + ans3[rounds])
        print('5 :' + ans4[rounds])
        q1 = input('Answer: \n')
        print(q1)
        # if q1 is not 1 or 2 or 3 or 4 or 5:
        #     print('Please select a valid answer')
        #     rounds = rounds
        if q1 is 1 or 2 or 3 or 4 or 5:
            total.append(int(q1))
            rounds = rounds + 1
            print('\n')
    else:
        print(total)
        print(sum(total))
questionaire()

progress = open("progress.txt", "w")
if 1 <= sum(total) <= 14:
    print('No problem')
    progress.write(time.ctime() + " SCORE:" + str(sum(total)) + " SEVERITY: No problem" + "\n")
elif 15 <= sum(total) <= 30:
    print('Slight Problem')
    progress.write(time.ctime() + " SCORE:" + str(sum(total)) + " SEVERITY: Slight Problem" + "\n")
elif 31 <= sum(total) <= 46:
    print('Moderate Problem')
    progress.write(time.ctime() + " SCORE:" + str(sum(total)) + " SEVERITY: Moderate Problem" + "\n")
elif 47 <= sum(total) <= 62:
    print('Severe Problem')
    progress.write(time.ctime() + " SCORE:" + str(sum(total)) + " SEVERITY: Severe Problem" + "\n")
elif 63 <= sum(total):
    print('Extreme Problem')
    progress.write(time.ctime() + " SCORE:" + str(sum(total)) + " SEVERITY: Extreme Problem" + "\n")
            
progress.close()

print ("INTERPRETING THE ADDICTION SEVERITY INDEX '\n'", "Total Score _______ Levels of Addiction '\n'",
      "1-14 _______ These ups and downs are considered normal '\n'", "15-30 _______ Slight Addiction '\n'",
      "31-46 ______ Moderate Addiction '\n'", "47-62 ______ Severe Addiction '\n'",
      "Over 63 ______ Extreme Addiction")
